"""Central configuration loader."""
frompathlibimportPath
importyaml
importos
importrandom
importnumpyasnp
defload_config(path:str=None)->dict:
    ifpathisNone:
        path=Path(__file__).resolve().parent.parent/"config.yaml"
withopen(path,"r")asf:
        cfg=yaml.safe_load(f)
if"RUN_SEED"inos.environ:
        cfg["project"]["seed"]=int(os.environ["RUN_SEED"])
returncfg
defseed_everything(seed:int=42):
    random.seed(seed)
np.random.seed(seed)
try:
        importtorch
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
exceptImportError:
        pass
CFG=load_config()
PROJECT_ROOT=Path(__file__).resolve().parent.parent