importjson
importos
importglob
importre
importpandasaspd
fromsklearn.model_selectionimporttrain_test_split
fromconfigimportload_config
defget_human_paragraphs(author_id,author_name,min_words,max_words,limit):
    raw_dir="data/raw"
files=glob.glob(os.path.join(raw_dir,f"{author_id}_*.txt"))
paragraphs=[]
forfpathinfiles:
        withopen(fpath,"r",encoding="utf-8")asf:
            text=f.read()
importsys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
fromsrc.utilsimportclean_text
text=clean_text(text)
blocks=text.split("\n\n")
forblockinblocks:
            block=block.strip().replace("\n"," ")
ifnotblock:continue
words=block.split()
ifmin_words<=len(words)<=max_words:
                paragraphs.append({
"text":block,
"label_class":"A",
"label_author":author_name,
"source_id":f"{author_name}_{author_id}"
})
iflen(paragraphs)>=limit:
                    returnparagraphs
returnparagraphs
defmain():
    config=load_config()
print("Extracting Class A (Human)...")
dickens_ids=[book["id"]forbookinconfig["gutenberg_books"]["Charles Dickens"]]
austen_ids=[book["id"]forbookinconfig["gutenberg_books"]["Jane Austen"]]
PER_BOOK=10
class_a=[]
ford_idindickens_ids:
        class_a.extend(get_human_paragraphs(d_id,"Dickens",100,200,PER_BOOK))
fora_idinausten_ids:
        class_a.extend(get_human_paragraphs(a_id,"Austen",100,200,PER_BOOK))
print(f"Got {len(class_a)} Class A paragraphs.")
withopen("data/processed/class_b.json","r")asf:
        raw_b=json.load(f)
class_b=[{"text":x["text"],"label_class":"B","label_author":"None","source_id":f"AI_Gen_{i}"}fori,xinenumerate(raw_b)]
print(f"Got {len(class_b)} Class B paragraphs.")
withopen("data/processed/class_c_dickens.json","r")asf:
        c_dickens=json.load(f)
withopen("data/processed/class_c_austen.json","r")asf:
        c_austen=json.load(f)
class_c=[{"text":x["text"],"label_class":"C","label_author":"Dickens","source_id":f"AI_Imp_D_{i}"}fori,xinenumerate(c_dickens)]
class_c+=[{"text":x["text"],"label_class":"C","label_author":"Austen","source_id":f"AI_Imp_A_{i}"}fori,xinenumerate(c_austen)]
print(f"Got {len(class_c)} Class C paragraphs.")
train_data,val_data,test_data=[],[],[]
importrandom
seed=config["project"]["seed"]
random.seed(seed)
forauthor_name,idsin[("Dickens",dickens_ids),("Austen",austen_ids)]:
        random.shuffle(ids)
train_ids=[f"{author_name}_{i}"foriinids[:3]]
val_ids=[f"{author_name}_{i}"foriinids[3:4]]
test_ids=[f"{author_name}_{i}"foriinids[4:]]
forpinclass_a:
            ifp["label_author"]==author_name:
                ifp["source_id"]intrain_ids:train_data.append(p)
elifp["source_id"]inval_ids:val_data.append(p)
elifp["source_id"]intest_ids:test_data.append(p)
importrandom
seed=config["project"]["seed"]
random.seed(seed)
random.shuffle(class_b)
random.shuffle(class_c)
defsplit_ai(data_list):
        n=len(data_list)
t_end=int(n*0.6)
v_end=int(n*0.8)
train_data.extend(data_list[:t_end])
val_data.extend(data_list[t_end:v_end])
test_data.extend(data_list[v_end:])
split_ai(class_b)
split_ai(class_c)
deffinalize(data_list,name):
        df=pd.DataFrame(data_list)
df["label"]=df["label_class"].map({"A":"Human","B":"AI_Generic","C":"AI_Impostor"})
df["author"]=df["label_author"]
df=df.sample(frac=1,random_state=config["project"]["seed"]).reset_index(drop=True)
df["sample_id"]=[f"{name}_{i}"foriinrange(len(df))]
df.to_csv(f"data/processed/{name}.csv",index=False)
returndf
train_df=finalize(train_data,"train")
val_df=finalize(val_data,"val")
test_df=finalize(test_data,"test")
print(f"Saved strict splits! Train: {len(train_df)}, Val: {len(val_df)}, Test: {len(test_df)}")
all_df=pd.concat([train_df,val_df,test_df],ignore_index=True)
all_df.to_csv("data/processed/all.csv",index=False)
if__name__=="__main__":
    main()